### PR TITLE
Added 6 models to db.json

### PR DESCRIPTION
**Pull request by ResidentChief**

### CODE REVIEW

**Comment by db0** [comment]
I don't think I want things like Gigachad. They are too specific to one thing and would dilute out already large model list for very minor usage. What do you think @AlRlC ?

**Comment by AlRlC** [comment]
> I don't think I want things like Gigachad. They are too specific to one thing and would dilute out already large model list for very minor usage. What do you think @AlRlC ?

I feel the same way. Imo we can add gigachad or similar models if the demand is high

**Comment by ResidentChief** [comment]
Did we want any of these 6 then?

**Comment by db0** [comment]
The others are fine I think

**Comment by ResidentChief** [comment]
Will delete and resubmit with the other 5 models then :)

**Pull request closed without merging**
